AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Fan out sample using AWS Lambda, SQS, SNS and Go
Parameters:
  WebhookURL:
    Type: String
  Channel:
    Type: String
  UserName:
    Type: String
  Icon:
    Type: String
  FileBucket:
    Type: String
Resources:
  WriteExtLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: artifact
      Handler: write_ext
      Runtime: go1.x
      Timeout: 10
      Tracing: Active
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ForExtLambdaQueue.Arn
  WriteExtLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${WriteExtLambda}
      RetentionInDays: 1

  WriteFileNameLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: artifact
      Handler: write_file_name
      Runtime: go1.x
      Timeout: 10
      Tracing: Active
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ForFileNameLambdaQueue.Arn
            BatchSize: 10
  WriteFileNameLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${WriteFileNameLambda}
      RetentionInDays: 1

  NotifierLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: artifact
      Handler: notifier
      Runtime: go1.x
      Timeout: 10
      Tracing: Active
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref S3FileTopic
      Environment:
        Variables:
          WEBHOOK_URL: !Ref WebhookURL
          CHANNEL: !Ref Channel
          USER_NAME: !Ref UserName
          ICON: !Ref Icon
  NotifierLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${NotifierLambda}
      RetentionInDays: 1

  SQSLambdaSample:
    Type: AWS::S3::Bucket
    DependsOn: SNSTopicPolicy
    Properties:
      BucketName: !Ref FileBucket
      NotificationConfiguration:
        TopicConfigurations:
          - Topic: !Ref S3FileTopic
            Event: s3:ObjectCreated:Put

  ForExtLambdaQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 20
      MessageRetentionPeriod: 60

  ForFileNameLambdaQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 20
      MessageRetentionPeriod: 60

  SQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal: "*"
          Action: sqs:*
          Resource: "*"
          Condition:
            StringEquals:
              aws:SourceArn:
                - !Ref S3FileTopic
      Queues:
        - !Ref ForExtLambdaQueue
        - !Ref ForFileNameLambdaQueue

  S3FileTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !GetAtt [ForExtLambdaQueue, Arn]
          Protocol: sqs
        - Endpoint: !GetAtt [ForFileNameLambdaQueue, Arn]
          Protocol: sqs
  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref S3FileTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effetc: Allow
            Action: sns:Publish
            Condition:
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:s3:::${FileBucket}"
            Principal:
              AWS: "*"
